# secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: YWRtaW4=  # Codificar en base64 el nombre de usuario (por ejemplo, admin)
  password: cGFzc3dvcmQ=  # Codificar en base64 la contraseña (por ejemplo, password)
